### ISSUE TITLE
报错了。。。请教。

### ISSUE THREAD

**Issue by mildrabbit** [shaonianzhentan/ha_baidu_map#10]
# Configure a default setup of Home Assistant (frontend, api, etc)

default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

ha_baidu_map:
   ak:oOzBCaXzWa9f3oPvxxxx后面的隐藏了哈
homekit:

以上是我的配置文件，提示

Invalid config
The following integrations and platforms could not be set up:

    ha_baidu_map

Please check your config.

没有搞懂为什么。。。

**Comment by shaonianzhentan** [comment]
注意一下格式啊，ak有两个空格缩进的

**Comment by mildrabbit** [comment]
嗯。谢谢。格式是搞定了，又提示ak无效，明明是网站上申请的。。还是提示无效
