### ISSUE TITLE
不能用，不知道为啥呢。

### ISSUE THREAD

**Issue by maybeloveu** [shaonianzhentan/ha_baidu_map#11]
提示如下
百度未授权使用地图API，可能是因为您提供的密钥不是有效的百度LBS开放平台密钥，或此密钥未对本应用的百度地图JavaScriptAPI授权。您可以访问如下网址了解如何获取有效的密钥：http://lbsyun.baidu.com/apiconsole/key#。

**Comment by shaonianzhentan** [comment]
如果不会配置就把ak删掉，请仔细阅读文档

**Comment by maybeloveu** [comment]
修改 了 ak 网址改成*可以用了。
