### ISSUE TITLE
能否考虑加个纠偏功能的开关

### ISSUE THREAD

**Issue by fkueyu** [shaonianzhentan/ha_baidu_map#16]
因为车辆GPS得到的是高德经纬度，转为百度经纬度后在百度坐标拾取里查询定位准确，但在插件中定位偏移了。调用百度纠偏接口后再查询坐标拾取其偏移位置和插件位置一致，应该是纠偏导致了位置的偏移。

**Comment by shaonianzhentan** [comment]
> 因为车辆GPS得到的是高德经纬度，转为百度经纬度后在百度坐标拾取里查询定位准确，但在插件中定位偏移了。调用百度纠偏接口后再查询坐标拾取其偏移位置和插件位置一致，应该是纠偏导致了位置的偏移。

唉，没有时间

**Comment by fkueyu** [comment]
已解决，将高德经纬度转换为wgs84传进去就好了。
