### ISSUE TITLE
日志一直在报错

### ISSUE THREAD

**Issue by Solismuchengxue** [shaonianzhentan/ha_baidu_map#2]
2020-02-03 00:49:55 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/.homeassistant/custom_components/ha_baidu_map/__init__.py", line 74, in interval
    attr =  dict(state.attributes)
AttributeError: 'NoneType' object has no attribute 'attributes'
一直报这个错,看不明白代码,如何解决

**Comment by shaonianzhentan** [comment]
这是没有判断state是否为none，你更新程序到1.0.6就好了

**Comment by Solismuchengxue** [comment]
> 这是没有判断state是否为none，你更新程序到1.0.6就好了

谢谢,升级之后好了

**Comment by cctv838126** [comment]
最新版本也是报这个错误。后来自己加了一句
    if 'activity' not in attr:
                continue
     if attr['activity'] is None:
                _LOGGER.info('地图测试-activity值为空：%s' % attr)
                continue
     arr = attr['activity'].split('-')

**Comment by shaonianzhentan** [comment]
> 最新版本也是报这个错误。后来自己加了一句
> if 'activity' not in attr:
> continue
> if attr['activity'] is None:
> _LOGGER.info('地图测试-activity值为空：%s' % attr)
> continue
> arr = attr['activity'].split('-')

那个record参数，是给使用GPSLogger定位设备使用的，如果使用我声明的配置，这个地方是一定会有值的

### 我完全不知道大家是否真的理解了这个参数的意义【笑哭】
