### ISSUE TITLE
最新版貌似系统出现报错！？

### ISSUE THREAD

**Issue by GWan1234** [shaonianzhentan/ha_baidu_map#21]
HA日志：
Logger: frontend.js.latest.202108040
Source: components/system_log/__init__.py:190
First occurred: 17:36:50 (15 occurrences)
Last logged: 20:21:07
http://*:8123/ha_baidu_map-local/2.4.3/ha-panel-baidu-map.js:759:120 Uncaught TypeError: Cannot read property 'attributes' of undefined
http://*:8123/ha_baidu_map-local/2.4.3/ha-panel-baidu-map.js:759:120 TypeError: undefined is not an object (evaluating 'this._hass.states[entity_id]['attributes']')
:0:0 Script error.
最后一个报错之前就有，但是清除浏览器缓存可以消失，时常复现，升级最新版之后出现上面两个。
再次感谢大佬的集成！

**Comment by shaonianzhentan** [comment]
> HA日志：
> Logger: frontend.js.latest.202108040
> Source: components/system_log/**init**.py:190
> First occurred: 17:36:50 (15 occurrences)
> Last logged: 20:21:07
> http://_:8123/ha_baidu_map-local/2.4.3/ha-panel-baidu-map.js:759:120 Uncaught TypeError: Cannot read property 'attributes' of undefined http://_:8123/ha_baidu_map-local/2.4.3/ha-panel-baidu-map.js:759:120 TypeError: undefined is not an object (evaluating 'this._hass.states[entity_id]['attributes']')
> :0:0 Script error.
> 最后一个报错之前就有，但是清除浏览器缓存可以消失，时常复现，升级最新版之后出现上面两个。
> 再次感谢大佬的集成！

你都把我搞懵了，我检查了一下代码，发现是你的配置的有问题，你配置的实体id没有属性值，所以异常了

**Comment by Tao173** [comment]
<img width="960" alt="baidu-map" src="https://user-images.githubusercontent.com/64321391/132880900-e114d50f-e807-4f7c-80ee-8191f0ae135a.png">

改了一下，也重新安装过，还是有这个错，，，能不能帮忙看看怎么解决

**Comment by Tao173** [comment]
另外集成添加方式显示终止，无法完成。
