### ISSUE TITLE
1.0.6版本显示不了地图

### ISSUE THREAD

**Issue by nichwang88** [shaonianzhentan/ha_baidu_map#3]
不知为何之前1.0版本能显示地图，刚刚更新了1.0.6反而显示不了地图，只能看到设备选项，地图一片白。百度地图APK是正常的，额度也够。

**Comment by shaonianzhentan** [comment]
重新安装之后，需要多刷新几下才能重新显示，这样做是为了避免缓存问题

**Comment by nichwang88** [comment]
解决了，我这次不是缓存问题，是AK问题，之前提交的浏览器端的AK能用的，升级以后不能用了，重新申请了服务端的AK解决了这个问题。
插件不错，感谢作者。有点建议，我没有用GPSLogger，不知道是否可以用iOS版的HA.app中的定位功能来绘制GPS定位轨迹。（另外，我的数据库是链接到群晖的MariaDB，不是系统自带的。）
