### ISSUE TITLE
大神 轨迹显示不出来 提示未授权 现在新建应用是 使用  服务端还是浏览器

### ISSUE THREAD

**Issue by lixmch** [shaonianzhentan/ha_baidu_map#6]
百度未授权使用地图API，可能是因为您提供的密钥不是有效的百度LBS开放平台密钥，或此密钥未对本应用的百度地图JavaScriptAPI授权。您可以访问如下网址了解如何获取有效的密钥：http://lbsyun.baidu.com/apiconsole/key#。

**Comment by shaonianzhentan** [comment]
浏览器
