### ISSUE TITLE
打开GPS运动轨迹时间是空白的

### ISSUE THREAD

**Issue by l2ktech** [shaonianzhentan/ha_baidu_map#8]
你好大佬，我在好几个主机中都发现，设备在地图中显示是正常的，但是打开GPS运动轨迹页面是空白的页面，什么都没有，GPS轨迹记录没法用，希望能帮忙找一下原因，感谢！

**Comment by shaonianzhentan** [comment]
GPS运动轨迹的生成，需要满足两个条件
1. 使用GPSLogger时一定要使用我文档中的配置，里面有特定的识别码`activity=%ACT-%DIST-%STARTTIMESTAMP`
2. 至少要有4个不重复的定位，才能生成一条正常的数据
