### ISSUE TITLE
更新115后，在外网透过反向代理，地图空白，内网访问正常，不知道是什么原因

### ISSUE THREAD

**Issue by heqirong** [shaonianzhentan/ha_baidu_map#9]

**Comment by heqirong** [comment]
重启hassio后，web端正常，安卓app的地图还是空白

**Comment by shaonianzhentan** [comment]
你目前用的是哪个版本，我这边3.1.1是没有问题

**Comment by shaonianzhentan** [comment]
> 重启hassio后，web端正常，安卓app的地图还是空白

我这边使用3.1.1版本，在APP里使用是正常的，你用的什么版本？

**Comment by heqirong** [comment]
> > 重启hassio后，web端正常，安卓app的地图还是空白
> 
> 我这边使用3.1.1版本，在APP里使用是正常的，你用的什么版本？

安卓app版本么，我用的2.4.1

**Comment by shaonianzhentan** [comment]
> 2.4.1

😂我说的是地图组件版本

**Comment by heqirong** [comment]
> > 2.4.1
> 
> 😂我说的是地图组件版本

额。。。我用的是8-12那个版本，readme没看到版本号啊，2.4后就是8月12日

**Comment by heqirong** [comment]
> > 2.4.1
> 
> 😂我说的是地图组件版本

确定了下我的地图组件版本是3.1.1，外网访问地图空白，Chrome开发者工具中的报错为This request has been blocked; the content must be served over HTTPS.

**Comment by shaonianzhentan** [comment]
> > > 2.4.1
> > 
> > 
> > 😂我说的是地图组件版本
> 
> 确定了下我的地图组件版本是3.1.1，外网访问地图空白，Chrome开发者工具中的报错为This request has been blocked; the content must be served over HTTPS.

新版本已经解决了这个问题
